# Generated by Django 4.2.1 on 2023-05-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_person_techskills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
