# Generated by Django 4.2.1 on 2023-05-26 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 5, 26, 6, 35, 49, 383964, tzinfo=datetime.timezone.utc), upload_to='blogimages'),
            preserve_default=False,
        ),
    ]
