# Generated by Django 4.2.1 on 2023-05-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
